### ISSUE TITLE
index.php

### ISSUE THREAD

**Issue by GordonArber** [ashwin47/Net-Neutral#17]
When I load the website, I get these warnings:

> Warning: session_start(): open(/storage/h2/897/728897/tmp/sess_eq46ltbnngkupbcnl59l2p61n1, O_RDWR) failed: No such file or directory (2) in /storage/h2/897/728897/public_html/facebook_start.php on line 4
> 
> Warning: session_start(): Failed to read session data: files (path: /storage/h2/897/728897/tmp) in /storage/h2/897/728897/public_html/facebook_start.php on line 4
> sudo apt-get install curl sudo apt-get install curl 
> Fatal error: Uncaught Facebook\Exceptions\FacebookSDKException: Sessions are not active. Please make sure session_start() is at the top of your script. in /storage/h2/897/728897/public_html/Facebook/PersistentData/FacebookSessionPersistentDataHandler.php:50 Stack trace: #0 /storage/h2/897/728897/public_html/Facebook/Helpers/FacebookRedirectLoginHelper.php(80): Facebook\PersistentData\FacebookSessionPersistentDataHandler->__construct() #1 /storage/h2/897/728897/public_html/Facebook/Facebook.php(322): Facebook\Helpers\FacebookRedirectLoginHelper->__construct(Object(Facebook\Authentication\OAuth2Client), NULL, NULL, NULL) #2 /storage/h2/897/728897/public_html/index.php(6): Facebook\Facebook->getRedirectLoginHelper() #3 {main} thrown in /storage/h2/897/728897/public_html/Facebook/PersistentData/FacebookSessionPersistentDataHandler.php on line 50
> 

Thoughts?

**Comment by ToxicFume** [comment]
When I load the website, I get these warnings:

`
Warning: session_start(): open(/storage/h2/897/728897/tmp/sess_eq46ltbnngkupbcnl59l2p61n1, O_RDWR) failed: No such file or directory (2) in /storage/h2/897/728897/public_html/facebook_start.php on line 4

Warning: session_start(): Failed to read session data: files (path: /storage/h2/897/728897/tmp) in /storage/h2/897/728897/public_html/facebook_start.php on line 4
sudo apt-get install curl sudo apt-get install curl 
Fatal error: Uncaught Facebook\Exceptions\FacebookSDKException: Sessions are not active. Please make sure session_start() is at the top of your script. in /storage/h2/897/728897/public_html/Facebook/PersistentData/FacebookSessionPersistentDataHandler.php:50 Stack trace: #0 /storage/h2/897/728897/public_html/Facebook/Helpers/FacebookRedirectLoginHelper.php(80): Facebook\PersistentData\FacebookSessionPersistentDataHandler->__construct() #1 /storage/h2/897/728897/public_html/Facebook/Facebook.php(322): Facebook\Helpers\FacebookRedirectLoginHelper->__construct(Object(Facebook\Authentication\OAuth2Client), NULL, NULL, NULL) #2 /storage/h2/897/728897/public_html/index.php(6): Facebook\Facebook->getRedirectLoginHelper() #3 {main} thrown in /storage/h2/897/728897/public_html/Facebook/PersistentData/FacebookSessionPersistentDataHandler.php on line 50` Thoughts?

**Comment by ashwin47** [comment]
storage readable?
